# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/density_calculator_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&proto/density_calculator_service.proto\x12\x11\x64\x65nsitycalculator\x1a\x1cgoogle/protobuf/struct.proto\">\n\x17\x43\x61lculateDensityRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\x9c\x03\n\x18\x43\x61lculateDensityResponse\x12\x1c\n\x14is_residential_found\x18\x01 \x01(\x08\x12\x18\n\x10residential_area\x18\x02 \x01(\t\x12\x1d\n\x15residential_area_size\x18\x03 \x01(\x01\x12\x19\n\x11is_building_found\x18\x04 \x01(\x08\x12\x11\n\tbuildings\x18\x05 \x01(\t\x12\x1d\n\x15living_buildings_area\x18\x06 \x01(\x01\x12!\n\x19non_living_buildings_area\x18\x07 \x01(\x01\x12\x1b\n\x13\x62uildings_area_size\x18\x08 \x01(\x01\x12\x15\n\rbuilt_percent\x18\t \x01(\x01\x12\x19\n\x11\x62uildings_density\x18\n \x01(\x01\x12 \n\x18living_buildings_density\x18\x0b \x01(\x01\x12\x12\n\nmax_people\x18\x0c \x01(\r\x12\x16\n\x0epeople_density\x18\r \x01(\r\x12\x1c\n\x14\x66ree_area_per_person\x18\x0e \x01(\x01\x32\x89\x01\n\x18\x44\x65nsityCalculatorService\x12m\n\x10\x43\x61lculateDensity\x12*.densitycalculator.CalculateDensityRequest\x1a+.densitycalculator.CalculateDensityResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.density_calculator_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATEDENSITYREQUEST']._serialized_start=91
  _globals['_CALCULATEDENSITYREQUEST']._serialized_end=153
  _globals['_CALCULATEDENSITYRESPONSE']._serialized_start=156
  _globals['_CALCULATEDENSITYRESPONSE']._serialized_end=568
  _globals['_DENSITYCALCULATORSERVICE']._serialized_start=571
  _globals['_DENSITYCALCULATORSERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
